--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t mak1806/node-server ."
      - "docker tag mak1806/node-server mak1806/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push mak1806/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"mak1806\" --password=\"khanadil1996\""
version: 0.1

